version: '2'
services:
  nchan_1:
    image: rsheremet/pubsub-bus-local:1.1.0
    ports:
     - "9123:80"
     - "9124:443"
    depends_on:
     - nchan-redis-server
    links:
     - nchan-redis-server
  nchan_2:
    image: rsheremet/pubsub-bus-local:1.1.0
    ports:
     - "9125:80"
     - "9126:443"
    depends_on:
     - nchan-redis-server
    links:
     - nchan-redis-server
  nchan-redis-server:
    image: redis:4-alpine
    ports:
      - "6379:6379"
